### ISSUE TITLE
Don't work, server sponge

### ISSUE THREAD

**Issue by Heriptik** [dominiccarrington/ShulkerInventory#2]
Hello, this mod work with sponge ?

If yes, i have an error : 

`[08:00:41] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.block.BlockShulkerBox.func_190954_c(Lnet/minecraft/block/Block;)Lnet/minecraft/item/EnumDyeColor;
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_221]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:308) [SpongeImplHooks.class:1.12.2-2838-7.1.7]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zje000(MinecraftServer.java:4716) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NoSuchMethodError: net.minecraft.block.BlockShulkerBox.func_190954_c(Lnet/minecraft/block/Block;)Lnet/minecraft/item/EnumDyeColor;
	at com.ragegamingpe.shulkerinvent.common.network.GuiHandler.createShuklerBoxInventory(GuiHandler.java:67) ~[GuiHandler.class:?]
	at com.ragegamingpe.shulkerinvent.common.network.GuiHandler.getServerGuiElement(GuiHandler.java:47) ~[GuiHandler.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.redirect$forgeImpl$updatePluginContainer$zpj000(NetworkRegistry.java:551) ~[NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:253) ~[NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:88) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550) ~[aed.class:?]
	at com.ragegamingpe.shulkerinvent.common.network.message.SlotMessage.handleMessage(SlotMessage.java:79) ~[SlotMessage.class:?]
	at com.ragegamingpe.shulkerinvent.common.network.Message.lambda$onMessage$1(Message.java:211) ~[Message.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_221]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 7 more`

I use this version (sponge and forge) : https://image.noelshack.com/fichiers/2019/52/5/1577430296-sponge-version.png

**Comment by dominiccarrington** [comment]
With that error it will not work on a sponge server. I will investigate the issue
